//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldskillsChina2016.md
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.Participation = new HashSet<Participation>();
            this.Shedule = new HashSet<Shedule>();
            this.Championship = new HashSet<Championship>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CompetitionGroupID { get; set; }
        public string NameEnglish { get; set; }
        public string NameRussian { get; set; }
        public string Code { get; set; }
        public string DefinitionRussian { get; set; }
        public string PlanBuildingFilePath { get; set; }
        public string InfrastructureFilePath { get; set; }
        public string WSI { get; set; }
        public Nullable<bool> IsTeam { get; set; }
        public string DefinitionEnglish { get; set; }
    
        public virtual CompetitionGroup CompetitionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participation> Participation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shedule> Shedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Championship> Championship { get; set; }
    }
}
