//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldskillsChina2016.md
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participation()
        {
            this.Result = new HashSet<Result>();
        }
    
        public int ID { get; set; }
        public string CompetitorNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ChampionshipID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> CompetitionID { get; set; }
    
        public virtual Championship Championship { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
    }
}
