//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldskillsChina2016.md
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int ChampionshipID { get; set; }
        public int SkillsID { get; set; }
        public string SponsorClassName { get; set; }
        public string Sponsor { get; set; }
        public decimal Amount { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Championship Championship { get; set; }
        public virtual Competition Competition { get; set; }
    }
}
